exports.elementos = {
    selectMenuSimulacao: 'li[id="menuform:simulacao"]',
    buttonNovaSimulacao: 'button[id="j_idt111"]',
    selectRegional: 'label[id="regional_label"]',
    inputNomeRegional: 'input[id="regional_filter"]',
    insertNomeRegional: 'li[class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all"]',
    searchResultRegional: 'ul[id="regional_items"]',
    selectConsultor: 'label[id="consultor_label"]',
    inputNomeConsultor: 'input[id="consultor_filter"]',
    searchResultConsulor: 'li[class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight"]',
    selectEspecie: 'label[id="especie_label"]',
    searchResultEspecie: 'li[class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all"]',
    selectRaca: 'label[id="raca_label"]',
    insertNomeRaca: 'input[id="raca_filter"]',
    searchResultRaca: 'ul[id="raca_items"]',
    insertNascimento: 'input[id="dtNasc_input"]',
    insertNomeProponente:'input[id="nomeCliente"]',
    insertMunicipio: 'input[id="municipioComplete_input"]',
    inertNomeMunicipio: 'span[id="municipioComplete"]',
    searchResultNomeMunicipio: 'span[id="municipioComplete_panel"]',
    insertTelCelular: 'input[id="telefone"]',
    insertEmail: 'input[id="email"]',
    buttonSalvarSimulacao: 'button[id="j_idt215"]',
    insertPesquisarNomeProponente: 'input[id="filtro"]',
    buttonPesquisarNomeProponente: 'button[id="j_idt121"]',
    selectTableSimulacao: 'tbody[class="ui-datatable-data ui-widget-content"]',
    buttonAbrirAdesao: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only rounded-button ui-button-info"]',
    inputValorAdesao: 'input[id="adesao_input"]',
    selectPlano: 'div[class="p-3 h-full"]',
    selectAdesao: 'tbody[id="tabelaResultado_data"]',
    selectTable: 'tr[class="ui-widget-content ui-datatable-even"]',
    selectP: 'div[class="col-12 lg:col-4 Fleft"]',
    inputNomePet: 'input[id="nomeAnimal"]',
    inputDescPelagem: 'input[id="dcPelagem"]',
    selectSexoPet: 'label[id="sexoAnimal_label"]',
    inputSexoAnimal: 'input[id="sexoAnimal_filter"]',
    searchResultSexoAnimal: 'div[id="sexoAnimal_panel"]',
    inputPesoPet: 'input[id="peso_input"]',
    buttonConfDadosAnimal: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only Fs16 ui-button-success"]',
    inputCpf: 'input[id="cpfContratante"]',
    inputDataNascimento: 'input[id="dtNascContratante_input"]',
    inputRgContratante: 'input[id="rgContratante"]',
    selectSexoContratante: 'label[id="sexoContratante_label"]',
    inputSexoContratante: 'input[id="sexoContratante_filter"]',
    searchResulSexoContratante: 'div[id="sexoContratante_panel"]',
    inputProfissao: 'input[id="profContratante_input"]',
    inputTelefone: 'input[id="telefone1"]',
    selectFormaPagamento: 'label[id="formaPagamento_label"]',
    inputFormaPagamento: 'input[id="formaPagamento_filter"]',
    searchResultFormaPagamento: 'div[id="formaPagamento_panel"]',
    buttonConfDadosContratante: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only Fs16 ui-button-success"]',
    inputCep:'input[id="cep"]', 
    inputNumeroLogradouro: 'input[id="numeroEndereco"]',
    inputComplemento: 'input[id="complemento"]',
    buttonConfEndereco: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only Fs16 ui-button-success"]',
    buttonSelecionarArquivo: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-fileupload-choose"]',
    selectArquivo: '[type="file"]',
    selectTipoArquivo: 'label[class="ui-selectonemenu-label ui-inputfield ui-corner-all"]',
    searchResultTipoArquivo: 'input[class="ui-selectonemenu-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all"]',
    selectOptionsAquivo: 'li[class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all"]',
    buttonConfArquivos: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only Fs16 ui-button-success"]',
    buttonAlertaArquivo: 'button[class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-confirm-popup-yes"]',
    selectMenuPVendas: 'li[id="menuform:analiseCadastral"]',
    inputNomeDoPet: 'input[id="nomeAnimal"]',
    inputNomeDoTutor: 'input[id="nomeContratante"]',
    selectSituacao: 'label[id="situacaoAdesao_label"]',
    searchResultSituacao: 'input[id="situacaoAdesao_filter"]',
    selectOptionsSituacao: 'li[class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all"]',
    buttonPesquisarAnaliseCadastral: 'button[id="pesquisar"]',
    buttonAcoesAnaliseCadastral: 'button[id="tabelaAnaliseCadastral:0:acoes_button"]',
    selectAprovar: 'a[id="aprovar"]',
    inputObservacaoAprovar: 'textarea[id="aprovarAnaliseForm:obs"]',
  


    

   


    
    




}